### ISSUE TITLE
Syntax and format

### ISSUE THREAD

**Issue by darkmorgoth-fl** [fetlife/translations#198]
Hi,

What's the actual syntax of the YML file? Is HTML allowed everywhere, or just on selected items?

How does quoting work e.g. in this case?:
```yml
page_title: You "MIGHT" Have Mail
```
I mean shouldn't it all be quoted like `"You \"MIGHT\" Have Mail"` or `'You "MIGHT" Have Mail'`?

How is the ampersand meant to be used? I've found pretty much all of the possible options:
```yml
    help_translate: Visit our <a class="silver" href="https://github.com/fetlife/translations">translation project</a> on GitHub and help make FetLife accessible to more of our kinky friends <span class="amp">&amp</span> communities.
    cb_fp: Allow my non-private posts to appear on Fresh&Pervy.
      fp: Fresh<span class="a-ampersand">&amp;</span>Pervy
      tips_header: Tips &amp; Tricks
```

Similarly the ellipsis is sometimes `&hellip;`, sometimes `...` and sometimes `…` (the unicode symbol). Or the apostrophe is sometimes ASCII `'` and sometimes unicode.
