### ISSUE TITLE
URLs to Give Context

### ISSUE THREAD

**Issue by johnbaku** [fetlife/translations#47]
Should we do something like this:

![translations_en_yml_at_master_ _fetlife_translations](https://cloud.githubusercontent.com/assets/22100/21106711/e8dafee2-c043-11e6-98c8-302a8fce193d.png)

to give context to whomever is helping out with translations?

cc/ @joaocunha @reneklacan @rakvat @yianni3000

**Comment by rakvat** [comment]
@johnbaku I'm not sure if that helps a lot because some pages can't be reached directly (e.g. signup step verify)

**Comment by yianni3000** [comment]
@johnbaku  when i was translating, the url would have been a big context help for me. Very good suggestion.

**Comment by joaocunha** [comment]
I see the value on this, but how do we tackle:

- dynamic URLs
- fetlife-web URLs that don't match vinyl
- URLs that can't be accessed directly

@rakvat @reneklacan @johnbaku thoughts?

**Comment by reneklacan** [comment]
I also see big value. I don't see it as a problem if some sections would be lacking url, it would be rare or worst case we can describe flow how to get there eg: `https://fetlife.com/settings -> press "Boom"`

**Comment by Two-Finger** [comment]
Maybe a single, separate file with only the URLs and no translatable strings inside?
So the language files stay clean of comments and changes are still easy to review.
And any changes to the URLs will happen in one place.

```yaml
# url-map.yml
---
en:
  signup: https://fetlife.com/signup_step_profile
  forgot_password:
    email: https://fetlife.com/users/password/new
    mobile: https://fetlife.com/users/password/new_via_phone
  guidelines:
    subnav:
      community: https://fetlife.com/guidelines/community
      content: https://fetlife.com/guidelines/content
      group_leader: https://fetlife.com/guidelines/group_leader
```
